// Code generated by "stringer -type=cipherSuiteId"; DO NOT EDIT

package dtls

import "fmt"

const _cipherSuiteId_name = "TLS_NULL_WITH_NULL_NULL"

var _cipherSuiteId_index = [...]uint8{0, 23}

func (i cipherSuiteId) String() string {
	if i >= cipherSuiteId(len(_cipherSuiteId_index)-1) {
		return fmt.Sprintf("cipherSuiteId(%d)", i)
	}
	return _cipherSuiteId_name[_cipherSuiteId_index[i]:_cipherSuiteId_index[i+1]]
}
